### ISSUE TITLE
Scabelity of Component

### ISSUE THREAD

**Issue by mh05** [NadeeshanEngineering/UIStepperController#1]
If the components frame is to big. The component is not scaling nicely. The stays totally on the left frame. This is noticeable when going to iPad
<img width="772" alt="scalinguistepper" src="https://user-images.githubusercontent.com/6358302/42552163-4f0574d8-84db-11e8-9d5b-8fc542535adf.png">

**Comment by heshantha-don** [comment]
Dear mh05,

Thank you for pointing me the issue with iPad layout. I just fixed the issue and committed a new source to the GitHub repo. I hope you would like the new UIStepperController with NSLayoutConstraints. Please find the new source with UIStepperController master repo. Cheers! 👍
